replicaCount: 2

image:
  repository: "<ACCOUNT_ID>.dkr.ecr.us-west-2.amazonaws.com/lesson-7-django-ecr"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

configmap:
  name: django-config

env:
  DJANGO_SETTINGS_MODULE: "project.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  # сюди перенеси свої змінні з теми 4, наприклад:
  # SECRET_KEY: "your-secret"
  # DATABASE_URL: "postgres://..."

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
